copyright = "Â© 2026 MAGGIE LEE"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "America/Phoenix"
timeout = "120s"
title = "MAGGIE LEE"
baseURL = ""

[security]
  enableInlineShortcodes = true

[params]
  defaultTheme = "light"
  description = ""
  title = "MAGGIE LEE"
  [params.author]
    email = "me@maggie.design"
    name = "Maggie Lee"
  [params.socialIcons]
    email = "mailto:me@maggie.design"
  [params.gallery]
    boxSpacing = 10
    targetRowHeight = 288
    targetRowHeightTolerance = 0.25

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.140.0"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]

[services]
  [services.rss]
    limit = 100